<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261007151528 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, setting_key VARCHAR(50) NOT NULL, setting_value TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_setting_tenant_key ON app_setting (tenant_id, setting_key)');
        $this->addSql('CREATE INDEX IDX_722938D59033212A ON app_setting (tenant_id)');
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password_hash VARCHAR(255) NOT NULL, roles JSON NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_tenant_email ON app_user (tenant_id, email)');
        $this->addSql('CREATE INDEX IDX_88BDF3E99033212A ON app_user (tenant_id)');
        $this->addSql('CREATE TABLE customer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, phone VARCHAR(30) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_customer_tenant ON customer (tenant_id)');
        $this->addSql('CREATE INDEX idx_customer_tenant_name ON customer (tenant_id, name)');
        $this->addSql('CREATE UNIQUE INDEX uniq_customer_tenant_phone ON customer (tenant_id, phone)');
        $this->addSql('CREATE UNIQUE INDEX uniq_customer_tenant_email ON customer (tenant_id, email)');
        $this->addSql('CREATE TABLE expense_allocation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, allocated_amount NUMERIC(12, 2) NOT NULL, allocation_pct NUMERIC(5, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, investment_expense_id INT NOT NULL, investment_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_allocation_expense_item ON expense_allocation (investment_expense_id, investment_item_id)');
        $this->addSql('CREATE INDEX IDX_EC501C239033212A ON expense_allocation (tenant_id)');
        $this->addSql('CREATE INDEX IDX_EC501C23EAEDD5EA ON expense_allocation (investment_expense_id)');
        $this->addSql('CREATE INDEX IDX_EC501C23AD058CBD ON expense_allocation (investment_item_id)');
        $this->addSql('CREATE TABLE inventory_movement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, movement_type VARCHAR(20) NOT NULL, reason_code VARCHAR(30) DEFAULT NULL, quantity_delta INT NOT NULL, unit_cost_snapshot NUMERIC(12, 2) DEFAULT NULL, current_unit_cost_snapshot NUMERIC(12, 2) DEFAULT NULL, reference_type VARCHAR(30) DEFAULT NULL, reference_id INT DEFAULT NULL, idempotency_key VARCHAR(120) NOT NULL, movement_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, notes VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, investment_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_movement_tenant_item ON inventory_movement (tenant_id, investment_item_id)');
        $this->addSql('CREATE INDEX idx_movement_tenant_date ON inventory_movement (tenant_id, movement_date)');
        $this->addSql('CREATE INDEX idx_movement_tenant_type ON inventory_movement (tenant_id, movement_type)');
        $this->addSql('CREATE INDEX idx_movement_reference ON inventory_movement (tenant_id, reference_type, reference_id, movement_type)');
        $this->addSql('CREATE UNIQUE INDEX uniq_movement_idempotency ON inventory_movement (idempotency_key)');
        $this->addSql('CREATE INDEX IDX_40972F669033212A ON inventory_movement (tenant_id)');
        $this->addSql('CREATE INDEX IDX_40972F66AD058CBD ON inventory_movement (investment_item_id)');
        $this->addSql('CREATE TABLE investment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(30) NOT NULL, investment_date DATE NOT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancelled_reason VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, base_currency VARCHAR(3) NOT NULL, usd_rate_snapshot NUMERIC(12, 4) DEFAULT NULL, current_usd_rate NUMERIC(12, 4) DEFAULT NULL, total_merchandise_cost NUMERIC(12, 2) NOT NULL, total_expenses NUMERIC(12, 2) NOT NULL, total_investment NUMERIC(12, 2) NOT NULL, allocation_method VARCHAR(20) NOT NULL, recovery_mode VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, last_revalued_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, created_by INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_investment_tenant_date ON investment (tenant_id, investment_date)');
        $this->addSql('CREATE INDEX idx_investment_tenant_status ON investment (tenant_id, status)');
        $this->addSql('CREATE INDEX idx_investment_tenant_confirmed ON investment (tenant_id, confirmed_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_investment_tenant_code ON investment (tenant_id, code)');
        $this->addSql('CREATE INDEX IDX_43CA0AD69033212A ON investment (tenant_id)');
        $this->addSql('CREATE INDEX IDX_43CA0AD6DE12AB56 ON investment (created_by)');
        $this->addSql('CREATE TABLE investment_expense (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(30) NOT NULL, description VARCHAR(255) DEFAULT NULL, amount NUMERIC(12, 2) NOT NULL, is_allocated BOOLEAN NOT NULL, usd_rate_snapshot NUMERIC(12, 4) DEFAULT NULL, amount_usd NUMERIC(12, 4) DEFAULT NULL, expense_date DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, investment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_expense_tenant_investment ON investment_expense (tenant_id, investment_id)');
        $this->addSql('CREATE INDEX IDX_925053459033212A ON investment_expense (tenant_id)');
        $this->addSql('CREATE INDEX IDX_925053456E1B4FD5 ON investment_expense (investment_id)');
        $this->addSql('CREATE TABLE investment_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit_cost NUMERIC(12, 2) NOT NULL, unit_cost_usd NUMERIC(12, 4) DEFAULT NULL, allocated_expense NUMERIC(12, 2) NOT NULL, allocated_expense_usd NUMERIC(12, 4) DEFAULT NULL, real_unit_cost NUMERIC(12, 2) NOT NULL, real_unit_cost_usd NUMERIC(12, 4) DEFAULT NULL, current_real_unit_cost NUMERIC(12, 2) NOT NULL, suggested_margin_pct NUMERIC(5, 2) NOT NULL, suggested_price NUMERIC(12, 2) NOT NULL, current_suggested_price NUMERIC(12, 2) NOT NULL, notes TEXT DEFAULT NULL, last_revalued_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, investment_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_item_tenant_investment ON investment_item (tenant_id, investment_id)');
        $this->addSql('CREATE INDEX idx_item_tenant_product ON investment_item (tenant_id, product_id)');
        $this->addSql('CREATE INDEX IDX_6C5A30C89033212A ON investment_item (tenant_id)');
        $this->addSql('CREATE INDEX IDX_6C5A30C86E1B4FD5 ON investment_item (investment_id)');
        $this->addSql('CREATE INDEX IDX_6C5A30C84584665A ON investment_item (product_id)');
        $this->addSql('CREATE TABLE investment_summary (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, total_investment NUMERIC(12, 2) NOT NULL, total_investment_current NUMERIC(12, 2) NOT NULL, total_revaluation_gain_loss NUMERIC(12, 2) NOT NULL, total_recovered NUMERIC(12, 2) NOT NULL, total_recovered_per_product NUMERIC(12, 2) NOT NULL, total_recovered_investment_first NUMERIC(12, 2) NOT NULL, total_recovered_current NUMERIC(12, 2) NOT NULL, total_gross_profit NUMERIC(12, 2) NOT NULL, total_recognized_profit NUMERIC(12, 2) NOT NULL, total_profit NUMERIC(12, 2) NOT NULL, total_profit_per_product NUMERIC(12, 2) NOT NULL, total_profit_investment_first NUMERIC(12, 2) NOT NULL, total_pending NUMERIC(12, 2) NOT NULL, total_pending_current NUMERIC(12, 2) NOT NULL, recovery_pct NUMERIC(5, 2) NOT NULL, units_sold INT NOT NULL, units_remaining INT NOT NULL, units_lost INT NOT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, investment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_summary_tenant ON investment_summary (tenant_id)');
        $this->addSql('CREATE INDEX idx_summary_tenant_pending ON investment_summary (tenant_id, total_pending)');
        $this->addSql('CREATE UNIQUE INDEX uniq_summary_investment ON investment_summary (investment_id)');
        $this->addSql('CREATE TABLE item_cost_revaluation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source VARCHAR(20) NOT NULL, old_rate NUMERIC(12, 4) NOT NULL, new_rate NUMERIC(12, 4) NOT NULL, old_real_unit_cost NUMERIC(12, 2) NOT NULL, new_real_unit_cost NUMERIC(12, 2) NOT NULL, old_suggested_price NUMERIC(12, 2) NOT NULL, new_suggested_price NUMERIC(12, 2) NOT NULL, quantity_snapshot INT NOT NULL, revaluation_gain_loss NUMERIC(14, 2) NOT NULL, reason VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, investment_item_id INT NOT NULL, usd_rate_id INT DEFAULT NULL, triggered_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_revaluation_tenant_item ON item_cost_revaluation (tenant_id, investment_item_id)');
        $this->addSql('CREATE INDEX idx_revaluation_tenant_date ON item_cost_revaluation (tenant_id, created_at)');
        $this->addSql('CREATE INDEX IDX_26AD94819033212A ON item_cost_revaluation (tenant_id)');
        $this->addSql('CREATE INDEX IDX_26AD9481AD058CBD ON item_cost_revaluation (investment_item_id)');
        $this->addSql('CREATE INDEX IDX_26AD948155F000E5 ON item_cost_revaluation (usd_rate_id)');
        $this->addSql('CREATE INDEX IDX_26AD948156090372 ON item_cost_revaluation (triggered_by)');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(12, 2) NOT NULL, currency VARCHAR(3) NOT NULL, usd_rate_snapshot NUMERIC(12, 4) DEFAULT NULL, payment_date DATE NOT NULL, method VARCHAR(20) NOT NULL, reference VARCHAR(100) DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, customer_id INT NOT NULL, sale_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_payment_tenant_date ON payment (tenant_id, payment_date)');
        $this->addSql('CREATE INDEX idx_payment_tenant_customer ON payment (tenant_id, customer_id)');
        $this->addSql('CREATE INDEX idx_payment_tenant_sale ON payment (tenant_id, sale_id)');
        $this->addSql('CREATE INDEX IDX_6D28840D9033212A ON payment (tenant_id)');
        $this->addSql('CREATE INDEX IDX_6D28840D9395C3F3 ON payment (customer_id)');
        $this->addSql('CREATE INDEX IDX_6D28840D4A7E4868 ON payment (sale_id)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, sku VARCHAR(50) DEFAULT NULL, category VARCHAR(80) DEFAULT NULL, default_margin_pct NUMERIC(5, 2) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_product_tenant ON product (tenant_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_tenant_sku ON product (tenant_id, sku)');
        $this->addSql('CREATE TABLE sale (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, currency VARCHAR(3) NOT NULL, sale_date DATE NOT NULL, total_amount NUMERIC(12, 2) NOT NULL, notes TEXT DEFAULT NULL, voided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, void_reason VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, created_by INT NOT NULL, investment_id INT NOT NULL, customer_id INT DEFAULT NULL, voided_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_sale_tenant_date ON sale (tenant_id, sale_date)');
        $this->addSql('CREATE INDEX idx_sale_tenant_investment ON sale (tenant_id, investment_id)');
        $this->addSql('CREATE INDEX idx_sale_tenant_customer ON sale (tenant_id, customer_id)');
        $this->addSql('CREATE INDEX IDX_E54BC0059033212A ON sale (tenant_id)');
        $this->addSql('CREATE INDEX IDX_E54BC005DE12AB56 ON sale (created_by)');
        $this->addSql('CREATE INDEX IDX_E54BC0056E1B4FD5 ON sale (investment_id)');
        $this->addSql('CREATE INDEX IDX_E54BC0059395C3F3 ON sale (customer_id)');
        $this->addSql('CREATE INDEX IDX_E54BC0051D5469C5 ON sale (voided_by)');
        $this->addSql('CREATE TABLE sale_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit_price NUMERIC(12, 2) NOT NULL, total_line NUMERIC(12, 2) NOT NULL, usd_rate_snapshot NUMERIC(12, 4) DEFAULT NULL, real_unit_cost_snapshot NUMERIC(12, 2) NOT NULL, current_cost_snapshot NUMERIC(12, 2) NOT NULL, cost_recovered NUMERIC(12, 2) NOT NULL, gross_profit_line NUMERIC(12, 2) NOT NULL, recognized_profit_line NUMERIC(12, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, sale_id INT NOT NULL, investment_item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_saleline_tenant_sale ON sale_line (tenant_id, sale_id)');
        $this->addSql('CREATE INDEX idx_saleline_tenant_item ON sale_line (tenant_id, investment_item_id)');
        $this->addSql('CREATE INDEX idx_saleline_tenant_created ON sale_line (tenant_id, created_at)');
        $this->addSql('CREATE INDEX IDX_6D5AC0139033212A ON sale_line (tenant_id)');
        $this->addSql('CREATE INDEX IDX_6D5AC0134A7E4868 ON sale_line (sale_id)');
        $this->addSql('CREATE INDEX IDX_6D5AC013AD058CBD ON sale_line (investment_item_id)');
        $this->addSql('CREATE TABLE tenant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, slug VARCHAR(80) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4E59C462989D9B62 ON tenant (slug)');
        $this->addSql('CREATE TABLE usd_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rate_date DATE NOT NULL, rate NUMERIC(12, 4) NOT NULL, is_correction BOOLEAN NOT NULL, source_note VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, supersedes_id INT DEFAULT NULL, created_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_usdrate_tenant_date ON usd_rate (tenant_id, rate_date)');
        $this->addSql('CREATE INDEX idx_usdrate_tenant_date_created ON usd_rate (tenant_id, rate_date, created_at)');
        $this->addSql('CREATE INDEX IDX_8B9C7F589033212A ON usd_rate (tenant_id)');
        $this->addSql('CREATE INDEX IDX_8B9C7F587A7685A8 ON usd_rate (supersedes_id)');
        $this->addSql('CREATE INDEX IDX_8B9C7F58DE12AB56 ON usd_rate (created_by)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE app_setting ADD CONSTRAINT FK_722938D59033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app_user ADD CONSTRAINT FK_88BDF3E99033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E099033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense_allocation ADD CONSTRAINT FK_EC501C239033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense_allocation ADD CONSTRAINT FK_EC501C23EAEDD5EA FOREIGN KEY (investment_expense_id) REFERENCES investment_expense (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense_allocation ADD CONSTRAINT FK_EC501C23AD058CBD FOREIGN KEY (investment_item_id) REFERENCES investment_item (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_movement ADD CONSTRAINT FK_40972F669033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_movement ADD CONSTRAINT FK_40972F66AD058CBD FOREIGN KEY (investment_item_id) REFERENCES investment_item (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE investment ADD CONSTRAINT FK_43CA0AD69033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE investment ADD CONSTRAINT FK_43CA0AD6DE12AB56 FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE investment_expense ADD CONSTRAINT FK_925053459033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE investment_expense ADD CONSTRAINT FK_925053456E1B4FD5 FOREIGN KEY (investment_id) REFERENCES investment (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE investment_item ADD CONSTRAINT FK_6C5A30C89033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE investment_item ADD CONSTRAINT FK_6C5A30C86E1B4FD5 FOREIGN KEY (investment_id) REFERENCES investment (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE investment_item ADD CONSTRAINT FK_6C5A30C84584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE investment_summary ADD CONSTRAINT FK_7142B8809033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE investment_summary ADD CONSTRAINT FK_7142B8806E1B4FD5 FOREIGN KEY (investment_id) REFERENCES investment (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE item_cost_revaluation ADD CONSTRAINT FK_26AD94819033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE item_cost_revaluation ADD CONSTRAINT FK_26AD9481AD058CBD FOREIGN KEY (investment_item_id) REFERENCES investment_item (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE item_cost_revaluation ADD CONSTRAINT FK_26AD948155F000E5 FOREIGN KEY (usd_rate_id) REFERENCES usd_rate (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE item_cost_revaluation ADD CONSTRAINT FK_26AD948156090372 FOREIGN KEY (triggered_by) REFERENCES app_user (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D4A7E4868 FOREIGN KEY (sale_id) REFERENCES sale (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale ADD CONSTRAINT FK_E54BC0059033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale ADD CONSTRAINT FK_E54BC005DE12AB56 FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale ADD CONSTRAINT FK_E54BC0056E1B4FD5 FOREIGN KEY (investment_id) REFERENCES investment (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale ADD CONSTRAINT FK_E54BC0059395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale ADD CONSTRAINT FK_E54BC0051D5469C5 FOREIGN KEY (voided_by) REFERENCES app_user (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_line ADD CONSTRAINT FK_6D5AC0139033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_line ADD CONSTRAINT FK_6D5AC0134A7E4868 FOREIGN KEY (sale_id) REFERENCES sale (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_line ADD CONSTRAINT FK_6D5AC013AD058CBD FOREIGN KEY (investment_item_id) REFERENCES investment_item (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE usd_rate ADD CONSTRAINT FK_8B9C7F589033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE usd_rate ADD CONSTRAINT FK_8B9C7F587A7685A8 FOREIGN KEY (supersedes_id) REFERENCES usd_rate (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE usd_rate ADD CONSTRAINT FK_8B9C7F58DE12AB56 FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE app_setting DROP CONSTRAINT FK_722938D59033212A');
        $this->addSql('ALTER TABLE app_user DROP CONSTRAINT FK_88BDF3E99033212A');
        $this->addSql('ALTER TABLE customer DROP CONSTRAINT FK_81398E099033212A');
        $this->addSql('ALTER TABLE expense_allocation DROP CONSTRAINT FK_EC501C239033212A');
        $this->addSql('ALTER TABLE expense_allocation DROP CONSTRAINT FK_EC501C23EAEDD5EA');
        $this->addSql('ALTER TABLE expense_allocation DROP CONSTRAINT FK_EC501C23AD058CBD');
        $this->addSql('ALTER TABLE inventory_movement DROP CONSTRAINT FK_40972F669033212A');
        $this->addSql('ALTER TABLE inventory_movement DROP CONSTRAINT FK_40972F66AD058CBD');
        $this->addSql('ALTER TABLE investment DROP CONSTRAINT FK_43CA0AD69033212A');
        $this->addSql('ALTER TABLE investment DROP CONSTRAINT FK_43CA0AD6DE12AB56');
        $this->addSql('ALTER TABLE investment_expense DROP CONSTRAINT FK_925053459033212A');
        $this->addSql('ALTER TABLE investment_expense DROP CONSTRAINT FK_925053456E1B4FD5');
        $this->addSql('ALTER TABLE investment_item DROP CONSTRAINT FK_6C5A30C89033212A');
        $this->addSql('ALTER TABLE investment_item DROP CONSTRAINT FK_6C5A30C86E1B4FD5');
        $this->addSql('ALTER TABLE investment_item DROP CONSTRAINT FK_6C5A30C84584665A');
        $this->addSql('ALTER TABLE investment_summary DROP CONSTRAINT FK_7142B8809033212A');
        $this->addSql('ALTER TABLE investment_summary DROP CONSTRAINT FK_7142B8806E1B4FD5');
        $this->addSql('ALTER TABLE item_cost_revaluation DROP CONSTRAINT FK_26AD94819033212A');
        $this->addSql('ALTER TABLE item_cost_revaluation DROP CONSTRAINT FK_26AD9481AD058CBD');
        $this->addSql('ALTER TABLE item_cost_revaluation DROP CONSTRAINT FK_26AD948155F000E5');
        $this->addSql('ALTER TABLE item_cost_revaluation DROP CONSTRAINT FK_26AD948156090372');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D9033212A');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D9395C3F3');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D4A7E4868');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD9033212A');
        $this->addSql('ALTER TABLE sale DROP CONSTRAINT FK_E54BC0059033212A');
        $this->addSql('ALTER TABLE sale DROP CONSTRAINT FK_E54BC005DE12AB56');
        $this->addSql('ALTER TABLE sale DROP CONSTRAINT FK_E54BC0056E1B4FD5');
        $this->addSql('ALTER TABLE sale DROP CONSTRAINT FK_E54BC0059395C3F3');
        $this->addSql('ALTER TABLE sale DROP CONSTRAINT FK_E54BC0051D5469C5');
        $this->addSql('ALTER TABLE sale_line DROP CONSTRAINT FK_6D5AC0139033212A');
        $this->addSql('ALTER TABLE sale_line DROP CONSTRAINT FK_6D5AC0134A7E4868');
        $this->addSql('ALTER TABLE sale_line DROP CONSTRAINT FK_6D5AC013AD058CBD');
        $this->addSql('ALTER TABLE usd_rate DROP CONSTRAINT FK_8B9C7F589033212A');
        $this->addSql('ALTER TABLE usd_rate DROP CONSTRAINT FK_8B9C7F587A7685A8');
        $this->addSql('ALTER TABLE usd_rate DROP CONSTRAINT FK_8B9C7F58DE12AB56');
        $this->addSql('DROP TABLE app_setting');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE expense_allocation');
        $this->addSql('DROP TABLE inventory_movement');
        $this->addSql('DROP TABLE investment');
        $this->addSql('DROP TABLE investment_expense');
        $this->addSql('DROP TABLE investment_item');
        $this->addSql('DROP TABLE investment_summary');
        $this->addSql('DROP TABLE item_cost_revaluation');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE sale');
        $this->addSql('DROP TABLE sale_line');
        $this->addSql('DROP TABLE tenant');
        $this->addSql('DROP TABLE usd_rate');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
